"""add avoid_task to chat_sessions

Revision ID: cf80942ccfcf
Revises: 90d879a2f60d
Create Date: 2026-05-31 14:40:18.173160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf80942ccfcf'
down_revision: Union[str, None] = '90d879a2f60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('avoid_task', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'avoid_task')
    # ### end Alembic commands ###
